### PR TITLE
dependencies; text edits; small fixes

### PR DESCRIPTION
**Pull request by danhammer**
A series of small fixes.  Note, however, that the site no longer works, after updates to the `water-series` API.  Now, the returned JSON only includes data from 1999-2011.  Something breaks.  See below:
screen shot 2016-06-06 at 12 41 43 am

### CODE REVIEW

**Comment by clementprdhomme** [comment]
Hi Dan, thanks for the changes.

I've just checked why the app displays this error and it seems it's because the `water-series` endpoint always return 0 for the `area` attribute.

Data returned by the endpoint

If you could change it, it should work again.

Clément

**Comment by danhammer** [comment]
Got it.  Fixed.  See [here](waterapp.enviro-service.appspot.com/water/series?coords=[[-119.8340606689453,39.24714385893248],[-119.8340606689453,39.32951742518054],[-119.77157592773436,39.32951742518054],[-119.77157592773436,39.24714385893248]]&begin=1999-01-01).  These fixes haven't been deployed to the web app.  Can you deploy?

**Comment by clementprdhomme** [comment]
It's been deployed 😉.

**Comment by danhammer** [comment]
Thank you @clementprdhomme!!  It looks wonderful.

**Pull request merged**
